name: Build Geode Mod

on:
  push:
    branches: ["*"]
  workflow_dispatch:

jobs:
  build:
    name: Build Mod
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Mod
        uses: geode-sdk/build-geode-mod@main
